sim_list:
  - SHORT_MOBILE-1
  - SHORT_MOBILE-2
  - SHORT_MOBILE-3
  - SHORT_MOBILE-4
  - LONG_MOBILE-1
  - LONG_MOBILE-2
  # - LONG_MOBILE-3
  # - LONG_MOBILE-4
  # - SHORT_SERVER-1
  # - SHORT_SERVER-2
  # - SHORT_SERVER-3
  # - SHORT_SERVER-4
  # - LONG_SERVER-1
  # - LONG_SERVER-2
  # - LONG_SERVER-3
  # - LONG_SERVER-4